language: node_js
node_js:
- '0.10'
- '0.11'
env:
  global:
    - secure: NF11l3g3JG1vfRurqYDptVHuQZtRCI9z4/9qCnNop6t5rLnAUXNjpiV7TddAnx3srKen1k1gCWfprYAnIel5jylwEyjeNgByjy/VoE4/FH7BehRQ1qalHhI9YAcBWSyoDmYlYRUHY4GUQDHyH+kTlp6FA5pXEn9v+rMgmTnP8vs=
    - secure: LafvQPT8oOJ++NoOnzFxGzIanBW4llt3Z0I3Gq76DTZV7Pw5vLJ/AMSJf/Rqs0TJlpVSDd4oIe9DVH9MxkKN7T/EYtTefgcNh5A3GhRBJ1fHwdHrH/ukJmMNY6W52dcvPvoCqFGHF6jlR6XHJ+ZqfC7qilh935oTtfpxXfnRBz0=
    - secure: Ohr9p2fIKJjZcv4qVergwQaOPhhWIAM06Efw0T8J5uKgUVqWrqY9YbPoSpCDVKHDLRC3/yBQEloY4WcMtrvr2+QntG3x3NwZlozzzhAqVm9yQg/PHH0Lb3N6My+aiTidzwGo/nMg6LnCwbGDh2ZeLXdA8aHxsKMwrxohx5xctU4=
    - secure: er5VnNTXt0Erknntx8S9hPN/yn6EhYsErKV7s1uDpCkqBpc5sY0MhbzyRrCeDsMisrjfrnXjrH2+2ZtKK3QJTmOCgON502i48SKTxAsStfPkFZtLPDuS/TkhjBp7nX63u7z33axJOUvyCG/JIFaCsRS11aVmGN4EcACAuaJXeJY=
    - secure: ZoWav1JkdxR7rSnaT2ARNj81Luyvj1ZJW65uXOUfGC9GomVvZ5/3APcf+q61jJVbIeRGVglPSpA9HGtGDqxE8b+NcSQ/z9HN0KUHX4tUV6Hj+Q6ZYCrm3U3fXhvq68FweUmVe2TJhtD2VEN+4M6s68bPmVtdAuEOdTX7IHVHX90=
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key:
    secure: LjW4VtSGBY5HEMof5iOkvwjSOCaZ/ngsE8PgbdxSTJt2E2IU+l+GBIz1F7N98jnCmIB1WnMP/d3/Zlt94ElkUoomT1C5qlH8RLuBXTzrg/UHQqK3GzFTCzz4GGhMUGSB5t+CxuqM5Zu3znbtLiosV2+7Yv0Jv0JeOyXzPCBToGo=
  app: leaf-issue-tracker
  on:
    repo: chrisharrington/Leaf
after_deploy:
  - sh updateBuildNumber.sh
